name = "homesafe"
compatibility_date = "2024-12-16"
pages_build_output_dir = "dist"

[env.production]
# KV Namespace for sessions in production
[[env.production.kv_namespaces]]
binding = "SESSION"
id = "temporary-session-store"
preview_id = "temporary-session-store"

[env.preview]
# KV Namespace for sessions in preview
[[env.preview.kv_namespaces]]
binding = "SESSION"
id = "temporary-session-store"
preview_id = "temporary-session-store"
